export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const UNSET_NOTIFICATION = "UNSET_NOTIFICATION";

export const SET_CLIENT = "SET_CLIENT";
export const UNSET_CLIENT = "UNSET_CLIENT";

export const ADD_COMMENT = "ADD_COMMENT";
